### ISSUE TITLE
Periodic (Cron) jobs

### ISSUE THREAD

**Issue by AxelTheGerman** [Betterment/delayed#17]
Hi and thank you for open sourcing this job framework!

I'm just starting to try it out but it looks quite promising. My mine motivator is the SQLite support.

One feature I'm missing (or haven't found yet) are periodic aka cron jobs. I have many use cases for some daily/weekly etc sync or update jobs.

Not sure if you think that should be part of `delayed` or are you maybe combining delayed with some kind of scheduler that runs alongside and simply queues jobs when their time has come? If so, any recommendations?

**Comment by hknaksu** [comment]
You may create rake tasks calling the jobs and invoke them using cron.

**Comment by AxelTheGerman** [comment]
I am hoping to avoid OS level integration, e.g. via cron directly.

But I think it makes sense to look for a separate scheduler which then queues jobs - it's just some job frameworks have taken on that complexity themselves (which has pros and cons of course)

**Comment by hknaksu** [comment]
take a look at whenever gem. it's for writing and deploying cron jobs.

**Comment by AxelTheGerman** [comment]
Finally RailsConf in person again, enjoy @smudge !

Yes that'd be interesting. especially around "as-close-to-once enqueue as possible"

**Comment by AxelTheGerman** [comment]
Going to have a look at `crono` too though it doesn't seem to be maintained anymore

https://github.com/plashchynski/crono

**Comment by AxelTheGerman** [comment]
Awesome thanks will have a look at that... came across clockwork too.

For now I actually use [Dokku Docker Local Scheduler](https://dokku.com/docs/deployment/schedulers/docker-local/) which is cron based as that's my deployment infrastructure.

But I think for anyone looking into that this discussion should help and maybe the DB backend for clockwork can be an option in the future - that diff is definitely super helpful.

Happy to discuss further and lend a hand, but also okay closing this issue for now.

Thanks for all your time and work!
